/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentDetail: typeof import('./src/components/agent/AgentDetail.vue')['default']
    AgentDevelopment: typeof import('./src/components/workspace/AgentDevelopment.vue')['default']
    ByCode: typeof import('./src/components/login/ByCode.vue')['default']
    ByPassword: typeof import('./src/components/login/ByPassword.vue')['default']
    ClassifierNodeDetail: typeof import('./src/components/workflow/node-details/ClassifierNodeDetail.vue')['default']
    CodeNodeDetail: typeof import('./src/components/workflow/node-details/CodeNodeDetail.vue')['default']
    Community: typeof import('./src/components/community/Community.vue')['default']
    ConditionNodeDetail: typeof import('./src/components/workflow/node-details/ConditionNodeDetail.vue')['default']
    EditProfile: typeof import('./src/components/profile/EditProfile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    ExtractNodeDetail: typeof import('./src/components/workflow/node-details/ExtractNodeDetail.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    HttpNodeDetail: typeof import('./src/components/workflow/node-details/HttpNodeDetail.vue')['default']
    KnowledgeNodeDetail: typeof import('./src/components/workflow/node-details/KnowledgeNodeDetail.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    LoopNodeDetail: typeof import('./src/components/workflow/node-details/LoopNodeDetail.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ModelNodeDetail: typeof import('./src/components/workflow/node-details/ModelNodeDetail.vue')['default']
    NodeDetailPanel: typeof import('./src/components/workflow/NodeDetailPanel.vue')['default']
    PluginNodeDetail: typeof import('./src/components/workflow/node-details/PluginNodeDetail.vue')['default']
    Profile: typeof import('./src/components/profile/Profile.vue')['default']
    ResourceLibrary: typeof import('./src/components/workspace/ResourceLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkflowCanvas: typeof import('./src/components/workflow/WorkflowCanvas.vue')['default']
    WorkflowNodeDetail: typeof import('./src/components/workflow/node-details/WorkflowNodeDetail.vue')['default']
    WorkflowNodeManager: typeof import('./src/components/workflow/WorkflowNodeManager.vue')['default']
    Workspace: typeof import('./src/components/workspace/Workspace.vue')['default']
  }
}
