/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentDetail: typeof import('./src/components/agent/AgentDetail.vue')['default']
    AgentDevelopment: typeof import('./src/components/workspace/AgentDevelopment.vue')['default']
    ByCode: typeof import('./src/components/login/ByCode.vue')['default']
    ByPassword: typeof import('./src/components/login/ByPassword.vue')['default']
    Community: typeof import('./src/components/community/Community.vue')['default']
    EditProfile: typeof import('./src/components/profile/EditProfile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    Home: typeof import('./src/components/home/Home.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Profile: typeof import('./src/components/profile/Profile.vue')['default']
    ResourceLibrary: typeof import('./src/components/workspace/ResourceLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkflowCanvas: typeof import('./src/components/workspace/WorkflowCanvas.vue')['default']
    Workspace: typeof import('./src/components/workspace/Workspace.vue')['default']
  }
}
