/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentDetail: typeof import('./src/components/agent/AgentDetail.vue')['default']
    AgentDevelopment: typeof import('./src/components/workspace/AgentDevelopment.vue')['default']
    ByCode: typeof import('./src/components/login/ByCode.vue')['default']
    ByPassword: typeof import('./src/components/login/ByPassword.vue')['default']
    ClassifierNodeDetail: typeof import('./src/components/workflow/node-details/ClassifierNodeDetail.vue')['default']
    CodeExplainPlugin: typeof import('./src/components/workflow/node-details/CodeExplainPlugin.vue')['default']
    CodeNodeDetail: typeof import('./src/components/workflow/node-details/CodeNodeDetail.vue')['default']
    Community: typeof import('./src/components/community/Community.vue')['default']
    ConditionNodeDetail: typeof import('./src/components/workflow/node-details/ConditionNodeDetail.vue')['default']
    CurrentTimePlugin: typeof import('./src/components/workflow/node-details/CurrentTimePlugin.vue')['default']
    EditProfile: typeof import('./src/components/profile/EditProfile.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    EndNodeDetail: typeof import('./src/components/workflow/node-details/EndNodeDetail.vue')['default']
    ExtractNodeDetail: typeof import('./src/components/workflow/node-details/ExtractNodeDetail.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    HttpNodeDetail: typeof import('./src/components/workflow/node-details/HttpNodeDetail.vue')['default']
    KnowledgeNodeDetail: typeof import('./src/components/workflow/node-details/KnowledgeNodeDetail.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    LoopNodeDetail: typeof import('./src/components/workflow/node-details/LoopNodeDetail.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ModelNodeDetail: typeof import('./src/components/workflow/node-details/ModelNodeDetail.vue')['default']
    Profile: typeof import('./src/components/profile/Profile.vue')['default']
    ResourceLibrary: typeof import('./src/components/workspace/ResourceLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartNodeDetail: typeof import('./src/components/workflow/node-details/StartNodeDetail.vue')['default']
    TimestampPlugin: typeof import('./src/components/workflow/node-details/TimestampPlugin.vue')['default']
    TimestampTransformPlugin: typeof import('./src/components/workflow/node-details/TimestampTransformPlugin.vue')['default']
    TimezoneSwitchPlugin: typeof import('./src/components/workflow/node-details/TimezoneSwitchPlugin.vue')['default']
    WeekdayCalculatorPlugin: typeof import('./src/components/workflow/node-details/WeekdayCalculatorPlugin.vue')['default']
    WorkflowCanvas: typeof import('./src/components/workflow/WorkflowCanvas.vue')['default']
    WorkflowNodeDetail: typeof import('./src/components/workflow/node-details/WorkflowNodeDetail.vue')['default']
    WorkflowNodeManager: typeof import('./src/components/workflow/WorkflowNodeManager.vue')['default']
    Workspace: typeof import('./src/components/workspace/Workspace.vue')['default']
  }
}
