# Generated by Django 5.1.7 on 2025-04-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('opening_line', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('persona', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('is_modifiable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('announcement_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word_content', models.CharField(max_length=100, unique=True)),
                ('replacement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=True)),
                ('ban_expire', models.DateTimeField(blank=True, null=True)),
                ('post_expire', models.DateTimeField(blank=True, null=True)),
                ('fans_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='backend.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('kb_id', models.AutoField(primary_key=True, serialize=False)),
                ('kb_name', models.CharField(max_length=100, unique=True)),
                ('kb_type', models.CharField(max_length=50)),
                ('kb_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueHistory',
            fields=[
                ('dialog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=5)),
                ('conversation_content', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=50)),
                ('operation_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.administrator')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('nodes', models.TextField()),
                ('edges', models.TextField()),
                ('is_builtin', models.BooleanField(default=False)),
                ('workflow_data', models.TextField()),
                ('view_points', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.agent')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.knowledgebase')),
            ],
            options={
                'unique_together': {('agent', 'kb')},
            },
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='backend.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='backend.user')),
            ],
            options={
                'unique_together': {('follower', 'followee')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'unique_together': {('user', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.agent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workflow')),
            ],
            options={
                'unique_together': {('agent', 'workflow')},
            },
        ),
    ]
