# Generated by Django 3.2.25 on 2025-04-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
