# Generated by Django 3.2.25 on 2025-04-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_knowledgebase_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Session',
        ),
    ]
