# Generated by Django 5.1.6 on 2025-05-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_conversation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
