# Generated by Django 5.1.7 on 2025-04-13 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_avatar_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='publisher',
        ),
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
