# Generated by Django 3.2.25 on 2025-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_workflow_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_published',
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('private', '私有'), ('check', '待审核'), ('published', '已发布')], default='private', max_length=10),
        ),
    ]
