# Generated by Django 3.2.25 on 2025-05-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20250503_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='backend.user'),
            preserve_default=False,
        ),
    ]
