# Generated by Django 3.2.25 on 2025-05-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20250503_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_published',
        ),
    ]
