# Generated by Django 3.2.25 on 2025-05-04 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_agent_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
