# Generated by Django 3.2.25 on 2025-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_agent_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='llm',
            field=models.TextField(blank=True, default='qwen-plus', null=True),
        ),
    ]
