# Generated by Django 5.2 on 2025-05-10 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_agent_llm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('process_result', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='backend.agent')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_agent_reports', to='backend.administrator')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reports', to='backend.user')),
            ],
        ),
    ]
