# Generated by Django 3.2.25 on 2025-05-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_agentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files_name',
            field=models.JSONField(blank=True, default=list, help_text='关联文件名列表'),
        ),
        migrations.AddField(
            model_name='message',
            name='thinking_chain',
            field=models.TextField(blank=True, help_text='AI 的思考过程记录', null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('申请', '申请'), ('好友', '好友'), ('拉黑', '拉黑')], default='申请', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_initiator', to='backend.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_receiver', to='backend.user')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_symmetric_contact'),
        ),
    ]
