# Generated by Django 3.2.25 on 2025-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20250511_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search',
            field=models.BooleanField(default=False),
        ),
    ]
