# Generated by Django 5.2 on 2025-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_message_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgechunk",
            name="level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
