# Generated by Django 3.2.25 on 2025-05-15 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_knowledgechunk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
