# Generated by Django 5.2 on 2025-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('admin', '管理员')], default='user', max_length=10),
        ),
    ]
