# Generated by Django 3.2.25 on 2025-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_agentreport_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='usage_amount',
            field=models.IntegerField(default=0),
        ),
    ]
