# Generated by Django 3.2.25 on 2025-05-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_userinteraction_usage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='usage_amount',
        ),
        migrations.AddField(
            model_name='agent',
            name='usage_amount',
            field=models.IntegerField(default=0),
        ),
    ]
