# Generated by Django 3.2.25 on 2025-06-01 06:09

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20250525_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgefile',
            name='file',
            field=models.FileField(upload_to=backend.models.user_upload_path),
        ),
    ]
